services:
  media-db:
    ports:
      - '27017:27017'
    container_name: media-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=management
    image: mongo:6.0

  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    command: minio server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console (Web UI)
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin};
      /usr/bin/mc mb myminio/${MINIO_DEFAULT_BUCKET:-default-bucket} --ignore-existing;
      /usr/bin/mc anonymous set public myminio/${MINIO_DEFAULT_BUCKET:-default-bucket};
      exit 0;
      "

  clamav-rest:
    image: ajilaag/clamav-rest
    ports:
      - "3310:9000"

volumes:
  minio_data: