name: Run tests, linting and type checking on pull request


on:
  pull_request:
    branches:
      - main


env:
  NODE_VERSION: 24

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # Needed to provision an ephemeral certificate for cosign
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint

  check-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Run type checks
        run: npm run check-ts

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # Needed to provision an ephemeral certificate for cosign
      id-token: write

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start database
        run: |
          docker compose -f docker-compose-tests.yml up -d

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }} # Use your project's Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        env:
          DB_USERNAME: admin
          DB_PASSWORD: admin
          DB_DATABASE: management
          DB_HOST: localhost
          DB_PORT: 27017
          S3_ENDPOINT: minio
          S3_PORT: 9000
          S3_ACCESS_KEY: minioadmin
          S3_SECRET_KEY: minioadmin
          S3_BUCKET_NAME_DEFAULT: default-bucket
          S3_BUCKET_NAME_PROFILE_PICTURES: default-bucket
          CLAMAV_URL: http://clamav-rest
          CLAMAV_PORT: 3310
        run: npm test